### ISSUE TITLE
About Application Error

### ISSUE THREAD

**Issue by neelparghi** [polonium31/jainish_blog#1]
![image](https://user-images.githubusercontent.com/67701255/123541109-59e5d980-d760-11eb-939a-f9d04de1729a.png)
Need to fix this EMAIL and PASSWORD code. It's leading to error. while after commenting these three line of code, your website is live.

**Comment by polonium31** [comment]
actually, it is not an error. due to a privacy issue, I add my mail as an environmental variable.
